### ISSUE TITLE
Add validation config as input

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle-action#2]
Since the GitHub Action itself is YAML, it would be nice if you could simply inline the configuration directly in the action without having to commit and refer to a file.

**Example usage**

```yaml
on: push

jobs:
  validate:
    name: Validate Kubernetes resources with Monokle
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@master
      - id: validate
        uses: kubeshop/monokle-action@v0.2.0
        with:
          path: __path_to_file_or_directory_with_kubernetes_yaml_files__
          config:
            plugins:
              practices: true
              kubernetes-schema: true
            rules:
              yaml-syntax/no-bad-alias: "warn"
              yaml-syntax/no-bad-directive: false
              practices/no-last-image: "err"
              practices/cpu-limit: "err"
            settings:
              kubernetes-schema:
                schemaVersion: v1.24.2
```
